export const translations = {
  en: {
    nav: {
      features: "Features",
      pricing: "Pricing",
      bandbrain: "BandBrain",
      language: "PT",
    },
    hero: {
      badge: "AI-Powered Music Intelligence",
      title: "The Weekly Signal",
      titleAccent: "Your Band Needs",
      subtitle:
        "Trends, sync opportunities, market analysis and actionable insights for independent musicians — curated by AI, delivered every Monday.",
      cta: "Get the Free Newsletter",
      ctaSub: "Join 0+ independent musicians. Free forever.",
    },
    form: {
      name: "Your name",
      email: "Your best email",
      button: "Subscribe — It's Free",
      sending: "Subscribing...",
      success: "You're in! Check your email.",
      error: "Something went wrong. Try again.",
    },
    features: {
      title: "What You Get Every Monday",
      items: [
        {
          icon: "🔥",
          title: "Top 3 News",
          desc: "The most important stories in the music industry, summarized and analyzed.",
        },
        {
          icon: "🎯",
          title: "Sync Opportunity",
          desc: "One actionable sync licensing tip you can act on this week.",
        },
        {
          icon: "📊",
          title: "Market Trend",
          desc: "Data-driven insight about where the industry is heading.",
        },
        {
          icon: "🛠️",
          title: "Tool of the Week",
          desc: "A curated tool or resource for independent musicians.",
        },
        {
          icon: "🎶",
          title: "AI-Curated Playlist",
          desc: "A weekly editorial playlist based on emerging trends.",
        },
        {
          icon: "💡",
          title: "Pro Tips",
          desc: "Exclusive strategies for growing your music career.",
        },
      ],
    },
    bandbrain: {
      badge: "Coming Soon",
      title: "BandBrain",
      titleAccent: "Your AI Band Manager",
      subtitle:
        "Social media calendars, press releases, setlists, monthly reports and playlist pitches — all generated by AI, tailored to your band.",
      features: [
        "30-day social media calendar",
        "Professional press releases",
        "Smart setlist suggestions",
        "Monthly analytics reports",
        "Playlist curator pitches",
      ],
      cta: "Join the Waitlist",
      ctaSub: "Be the first to know when BandBrain launches.",
    },
    pricing: {
      title: "Simple Pricing",
      free: {
        name: "TuneSignal Free",
        price: "Free",
        period: "forever",
        features: [
          "Weekly newsletter",
          "Top 3 news digest",
          "Market trends",
          "Tool recommendations",
        ],
        cta: "Subscribe Now",
      },
      premium: {
        name: "TuneSignal Premium",
        price: "R$29.90",
        period: "/month",
        features: [
          "Everything in Free",
          "Exclusive sync opportunities",
          "Deep market analysis",
          "Early access to BandBrain",
          "Priority support",
        ],
        cta: "Subscribe Now",
      },
      essencial: {
        name: "BandBrain Essencial",
        price: "R$47",
        period: "/month",
        features: [
          "Everything in Premium",
          "Social media calendar (30 days)",
          "Professional press releases",
          "Setlist strategies",
          "Monthly strategy reports",
        ],
        cta: "Start Free Trial",
      },
      pro: {
        name: "BandBrain Pro",
        price: "R$97",
        period: "/month",
        features: [
          "Everything in Essencial",
          "Unlimited calendars & reports",
          "Playlist curator pitches",
          "Advanced analytics",
          "Priority support",
        ],
        cta: "Start Free Trial",
      },
    },
    footer: {
      copy: "© 2026 Verelus. All rights reserved.",
      tagline: "Music intelligence platform by Verelus.",
    },
  },
  pt: {
    nav: {
      features: "Recursos",
      pricing: "Preços",
      bandbrain: "BandBrain",
      language: "EN",
    },
    hero: {
      badge: "Inteligência Musical com IA",
      title: "O Sinal Semanal",
      titleAccent: "Que Sua Banda Precisa",
      subtitle:
        "Tendências, oportunidades de sync, análises de mercado e insights acionáveis para músicos independentes — curados por IA, toda segunda-feira.",
      cta: "Receba a Newsletter Grátis",
      ctaSub: "Junte-se a 0+ músicos independentes. Grátis pra sempre.",
    },
    form: {
      name: "Seu nome",
      email: "Seu melhor email",
      button: "Inscrever-se — É Grátis",
      sending: "Inscrevendo...",
      success: "Você está dentro! Confira seu email.",
      error: "Algo deu errado. Tente novamente.",
    },
    features: {
      title: "O Que Você Recebe Toda Segunda",
      items: [
        {
          icon: "🔥",
          title: "Top 3 Notícias",
          desc: "As histórias mais importantes da indústria musical, resumidas e analisadas.",
        },
        {
          icon: "🎯",
          title: "Oportunidade de Sync",
          desc: "Uma dica acionável de licenciamento sync para essa semana.",
        },
        {
          icon: "📊",
          title: "Tendência de Mercado",
          desc: "Insight baseado em dados sobre para onde a indústria está indo.",
        },
        {
          icon: "🛠️",
          title: "Ferramenta da Semana",
          desc: "Uma ferramenta ou recurso curado para músicos independentes.",
        },
        {
          icon: "🎶",
          title: "Playlist Curada por IA",
          desc: "Uma playlist editorial semanal baseada em tendências emergentes.",
        },
        {
          icon: "💡",
          title: "Dicas Pro",
          desc: "Estratégias exclusivas para alavancar sua carreira musical.",
        },
      ],
    },
    bandbrain: {
      badge: "Em Breve",
      title: "BandBrain",
      titleAccent: "Seu Gerente de Banda IA",
      subtitle:
        "Calendários de redes sociais, press releases, setlists, relatórios mensais e pitches para playlists — tudo gerado por IA, personalizado para sua banda.",
      features: [
        "Calendário de 30 dias para redes sociais",
        "Press releases profissionais",
        "Sugestões inteligentes de setlist",
        "Relatórios mensais de métricas",
        "Pitches para curadores de playlists",
      ],
      cta: "Entrar na Lista de Espera",
      ctaSub: "Seja o primeiro a saber quando o BandBrain lançar.",
    },
    pricing: {
      title: "Preços Simples",
      free: {
        name: "TuneSignal Grátis",
        price: "Grátis",
        period: "pra sempre",
        features: [
          "Newsletter semanal",
          "Top 3 notícias",
          "Tendências de mercado",
          "Recomendações de ferramentas",
        ],
        cta: "Inscreva-se Agora",
      },
      premium: {
        name: "TuneSignal Premium",
        price: "R$29.90",
        period: "/mês",
        features: [
          "Tudo do plano Grátis",
          "Oportunidades exclusivas de sync",
          "Análises profundas de mercado",
          "Acesso antecipado ao BandBrain",
          "Suporte prioritário",
        ],
        cta: "Inscreva-se Agora",
      },
      essencial: {
        name: "BandBrain Essencial",
        price: "R$47",
        period: "/mês",
        features: [
          "Tudo do plano Premium",
          "Calendário de redes sociais (30 dias)",
          "Press releases profissionais",
          "Estratégias de setlist",
          "Relatórios mensais de estratégia",
        ],
        cta: "Teste Grátis",
      },
      pro: {
        name: "BandBrain Pro",
        price: "R$97",
        period: "/mês",
        features: [
          "Tudo do plano Essencial",
          "Calendários & relatórios ilimitados",
          "Pitches para curadores de playlists",
          "Análises avançadas",
          "Suporte prioritário",
        ],
        cta: "Teste Grátis",
      },
    },
    footer: {
      copy: "© 2026 Verelus. Todos os direitos reservados.",
      tagline: "Plataforma de inteligência musical da Verelus.",
    },
  },
};
